version = "1"

name = "Psalm Analyzer"
description = "Run Psalm static analyser macro for DeepSource"
visibility = "public"
category = "language"

[analyzer]
  command = "php /app/bin/analyze"

[build]
  image = "alpine:3.14"
  steps = """
    apk update && apk add --no-cache make && rm -rf /var/cache/apk/*
    cp -r . /app
    cd /app/.deepsource/analyzer && make build
  """
